blank_issues_enabled: false
contact_links:
  - name: Ich wurde gebannt
    url: https://timolia.de/discord
    about: Bitte erstelle ein Ticket in support channel
  - name: Ich brauche hilfe
    url: https://timolia.de/discord
    about: Bitte nutze cummunitysupport auf dem discord
