name: Minecraft Bug melden
description: Melde einen Bug der dir auf dem Minecraft-Netzwerk aufgefallen ist
body:
  - type: textarea
    id: the-bug
    attributes:
      label: Fehlerbeschreibung
      description: Bitte beschreibe den Fehler. Fügen Sie **Details** ein, die Sie für notwendig erachten. Wenn möglich Schritte zum reproduozieren
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: Client version
      description: Version deines spiels
      placeholder: e.g. vanilla 1.18.2 or labymod 1.20.1
    validations:
      required: true
  - type: input
    id: account
    attributes:
      label: Aktueller Minecraftname
      placeholder: McExpertDE
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Aufgetretene Fehlermeldungen
    validations:
      required: true
  - type: input
    id: meta
    attributes:
      label: Wann und wo ist der Fehler aufgetreten?
      description: Deinen aktuellen Server findest du im Tab
      placeholder: Auf games1 28.10.2023 ~9:44
    validations:
      required: true
